### ISSUE TITLE
Unable to access APL documents using getResourceAsStream().Always returns null.

### ISSUE THREAD

**Issue by sai6a** [alexa-samples/skill-sample-java-movie-quotes-quiz#2]
Unable to access APL documents using getResourceAsStream().Always returns null.

**Comment by pbheemag** [comment]
Hi @sai6a ,
Could you kindly raise an issue in the format mentioned [here](https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/new). Providing the context would help understand the issue better and expedite the process of fixing it.

**Comment by pbheemag** [comment]
Closing this ticket due to developer inactivity. Please feel free to re-open this ticket if the issue persists.
